// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateChatServerResponse create chat server response
//
// swagger:model CreateChatServerResponse
type CreateChatServerResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this create chat server response
func (m *CreateChatServerResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create chat server response based on context it is used
func (m *CreateChatServerResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateChatServerResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateChatServerResponse) UnmarshalBinary(b []byte) error {
	var res CreateChatServerResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
