x-common-variables: &common-variables
  DB_HOST: "host.docker.internal"
  JAEGER_HOST: "jaeger:6831"
  JAEGER_AGENT_HOST: jaeger
  JAEGER_AGENT_PORT: 6831

services:
  chatmessages:
    build: chatmessages/
    command: ./main
    environment:
      <<: *common-variables
      JAEGER_SERVICE_NAME: "chatmessages"
    ports:
      - "8081:8080"  # REST API
      - "9091:9090"  # gRPC
      - "8888:8888"  # Swagger UI
  chatservers:
    build: chatservers/
    command: ./main
    environment:
      <<: *common-variables
      JAEGER_SERVICE_NAME: "chatservers"
    ports:
      - "8082:8080"
  users:
    build: users/
    command: ./main
    environment:
      <<: *common-variables
      JAEGER_SERVICE_NAME: "users"
    ports:
      - "8083:8080"
  ###################
  # jaeger
  ###################
  jaeger:
    image: jaegertracing/all-in-one:1.48
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp" # jaeger-client
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # web
      - "14268:14268"
      - "9411:9411"
