services:
  messages:
    build: messages/
    command: ./main
    ports:
      - "8081:8080"
  servers:
    build: servers/
    command: ./main
    ports:
      - "8082:8080"
  users:
    build: users/
    command: ./main
    ports:
      - "8083:8080"
