services:
  chatmessages:
    build: chatmessages/
    command: ./main
    environment:
      DB_HOST: "host.docker.internal"
    ports:
      - "8081:8080"  # REST API
      - "9091:9090"  # gRPC
      - "8888:8888"  # Swagger UI
  chatservers:
    build: chatservers/
    command: ./main
    environment:
      DB_HOST: "host.docker.internal"
    ports:
      - "8082:8080"
  users:
    build: users/
    command: ./main
    environment:
      DB_HOST: "host.docker.internal"
    ports:
      - "8083:8080"
