apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-v1
  namespace: main
  labels:
    app: users
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
        version: "1.0" # Used in service.yml (spec/selector/version) for routing traffic
    spec:
      containers:
        - name: users-container
          image: mgrigoriev/users:v1
          ports:
            - containerPort: 8080
