apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: main
spec:
  type: LoadBalancer
  selector:
    app: users
    version: "1.0"  # Update to "2.0" after applying and testing deployment-v2
  ports:
    - name: http
      protocol: TCP
      targetPort: 8080
      port: 83
