apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: main
spec:
  type: LoadBalancer
  selector:
    app: users
  ports:
    - name: http
      protocol: TCP
      targetPort: 8080
      port: 83
