// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateFriendshipResponse create friendship response
//
// swagger:model CreateFriendshipResponse
type CreateFriendshipResponse struct {

	// id
	ID int64 `json:"id,omitempty"`
}

// Validate validates this create friendship response
func (m *CreateFriendshipResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create friendship response based on context it is used
func (m *CreateFriendshipResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateFriendshipResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateFriendshipResponse) UnmarshalBinary(b []byte) error {
	var res CreateFriendshipResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
