apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-v2
  namespace: main
  labels:
    app: users
spec:
  replicas: 0
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: mgrigoriev/users:v2
          ports:
            - containerPort: 8080
